apiVersion: apps/v1
kind: Deployment
metadata:
 name: pubsub
spec:
 selector:
   matchLabels:
     app: pubsub
 template:
   metadata:
     labels:
       app: pubsub
   spec:
     containers:
     - name: subscriber
       image: nginx
