apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
 name: pubsub
spec:
 minReplicas: 1
 maxReplicas: 5
 metrics:
 - external:
     metric:
      name: pubsub.googleapis.com|subscription|num_undelivered_messages
      selector:
        matchLabels:
           resource.labels.subscription_id: echo-read
           resource.labels.project_id: refined-magp-36798887 #modify this with your pubsub project id.
     target:
       type: AverageValue
       averageValue: 2
   type: External
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: pubsub
